// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taglib.proto

package org.cocolian.mysql.taglib;

public final class Taglib {
  private Taglib() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.cocolian.mysql.taglib.Taglib.tableOption);
    registry.add(org.cocolian.mysql.taglib.Taglib.columnOption);
    registry.add(org.cocolian.mysql.taglib.Taglib.alias);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int TABLE_OPTION_FIELD_NUMBER = 60000;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      org.cocolian.mysql.taglib.TableMessageOption> tableOption = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.cocolian.mysql.taglib.TableMessageOption.class,
        org.cocolian.mysql.taglib.TableMessageOption.getDefaultInstance());
  public static final int COLUMN_OPTION_FIELD_NUMBER = 60001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      org.cocolian.mysql.taglib.ColumnFieldOption> columnOption = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.cocolian.mysql.taglib.ColumnFieldOption.class,
        org.cocolian.mysql.taglib.ColumnFieldOption.getDefaultInstance());
  public static final int ALIAS_FIELD_NUMBER = 60002;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      org.cocolian.mysql.taglib.ColumnType> alias = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        org.cocolian.mysql.taglib.ColumnType.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TableMessageOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TableMessageOption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ColumnFieldOption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ColumnFieldOption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014taglib.proto\032 google/protobuf/descript" +
      "or.proto\"S\n\022TableMessageOption\022\022\n\ntable_" +
      "name\030\001 \002(\t\022\024\n\014name_pattern\030\002 \001(\t\022\023\n\013prim" +
      "ary_key\030\003 \001(\t\"h\n\021ColumnFieldOption\022\023\n\013co" +
      "lumn_name\030\001 \001(\t\022 \n\013column_type\030\002 \001(\0162\013.C" +
      "olumnType\022\034\n\024need_encrypted_store\030\003 \001(\010*" +
      "o\n\nColumnType\022\013\n\007VARCHAR\020\001\022\007\n\003INT\020\002\022\n\n\006B" +
      "IGINT\020\003\022\n\n\006DOUBLE\020\004\022\t\n\005FLOAT\020\005\022\013\n\007DECIMA" +
      "L\020\006\022\014\n\010DATETIME\020\007\022\r\n\tTIMESTAMP\020\010:L\n\014tabl" +
      "e_option\022\037.google.protobuf.MessageOption" +
      "s\030\340\324\003 \001(\0132\023.TableMessageOption:J\n\rcolumn" +
      "_option\022\035.google.protobuf.FieldOptions\030\341" +
      "\324\003 \001(\0132\022.ColumnFieldOption:?\n\005alias\022!.go" +
      "ogle.protobuf.EnumValueOptions\030\342\324\003 \001(\0162\013" +
      ".ColumnTypeB\035\n\031org.cocolian.mysql.taglib" +
      "P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_TableMessageOption_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TableMessageOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TableMessageOption_descriptor,
        new java.lang.String[] { "TableName", "NamePattern", "PrimaryKey", });
    internal_static_ColumnFieldOption_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ColumnFieldOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ColumnFieldOption_descriptor,
        new java.lang.String[] { "ColumnName", "ColumnType", "NeedEncryptedStore", });
    tableOption.internalInit(descriptor.getExtensions().get(0));
    columnOption.internalInit(descriptor.getExtensions().get(1));
    alias.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
