// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.cocolian.mysql.foo;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Foo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Foo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\032\014taglib.proto\"u\n\003Foo\022$\n\004col" +
      "1\030\001 \002(\tB\026\212\246\035\006\n\004col1\212\246\035\002\020\001\212\246\035\002\030\001\022\030\n\004col2\030" +
      "\002 \001(\005B\n\212\246\035\006\n\004col2\022\024\n\004col3\030\003 \001(\001B\006\212\246\035\002\020\004:" +
      "\030\202\246\035\n\n\010test_foo\202\246\035\006\032\004col1B\032\n\026org.cocolia" +
      "n.mysql.fooP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.cocolian.mysql.taglib.Taglib.getDescriptor(),
        }, assigner);
    internal_static_Foo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Foo_descriptor,
        new java.lang.String[] { "Col1", "Col2", "Col3", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.cocolian.mysql.taglib.Taglib.columnOption);
    registry.add(org.cocolian.mysql.taglib.Taglib.tableOption);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.cocolian.mysql.taglib.Taglib.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
