// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taglib.proto

package org.cocolian.mysql.taglib;

public interface TableMessageOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TableMessageOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *标识数据库中的表名
   * </pre>
   *
   * <code>required string table_name = 1;</code>
   */
  boolean hasTableName();
  /**
   * <pre>
   *标识数据库中的表名
   * </pre>
   *
   * <code>required string table_name = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <pre>
   *标识数据库中的表名
   * </pre>
   *
   * <code>required string table_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   *分表分库时的表名pattern;
   * </pre>
   *
   * <code>optional string name_pattern = 2;</code>
   */
  boolean hasNamePattern();
  /**
   * <pre>
   *分表分库时的表名pattern;
   * </pre>
   *
   * <code>optional string name_pattern = 2;</code>
   */
  java.lang.String getNamePattern();
  /**
   * <pre>
   *分表分库时的表名pattern;
   * </pre>
   *
   * <code>optional string name_pattern = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamePatternBytes();

  /**
   * <pre>
   *主键字段， 默认为空
   * </pre>
   *
   * <code>optional string primary_key = 3;</code>
   */
  boolean hasPrimaryKey();
  /**
   * <pre>
   *主键字段， 默认为空
   * </pre>
   *
   * <code>optional string primary_key = 3;</code>
   */
  java.lang.String getPrimaryKey();
  /**
   * <pre>
   *主键字段， 默认为空
   * </pre>
   *
   * <code>optional string primary_key = 3;</code>
   */
  com.google.protobuf.ByteString
      getPrimaryKeyBytes();
}
